pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

snowFlake:
  workInfo:
    datacenterId: 1
    machineId: 1

spring:
  session:
    store-type: redis
  application:
    name: system-administration
  http:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
    multipart:
      max-file-size: 1Mb      # Max file size，默认1M
      max-request-size: 2Mb   # Max request size，默认10M
  profiles:
    active:
#    - dev
#    - redis-dev
#    - test
#    - redis-test
    - pro
    - redis-pro
mybatis:
  type-aliases-package: com.by.crm.sysconfig.model
  mapperLocations: classpath*:mybatis/mapper/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mapper:
 not-empty: false
 identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
besedir: sysconfig

hystrix:
  command:
    default:
      execution:
        timeout:
          enable: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000

feign.hystrix.enabled: true
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 30000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: false

server:
  tomcat:
    uri-encoding: UTF-8

#验证码配置参数
verify:
  pic:
    height: 30
    width: 100
    letter-qty: 4
register:
  text: true
#移动端使用由后端处理过的配置化菜单权限信息
permission:
 map:
  customerManagement: 客户管理
  workLogManagement: 日常工作
  channelManagement: 渠道管理
  productManagement: 产品库管理
  orderManagement: 订单管理
  telephoneManagement: 电话营销
  designManagement: 量尺管理
  baiqiangManagement: 门店联赛
  collegeManagement: 移动商学院
  arrivalManagement: 到货管理
  installManagement: 安装管理
  caseInfoManagement: 案例库
  assistantManagement: 助销工具
  noticeManagement: 通知公告
  reportManagement: 报表中心
  targetManagement: 目标管理
  onlineRetailers: 电商引流
